A few optimizations that speedup training
OML-Team/open-metric-learning pull request #627
Opened 2024-09-28 12:35 UTC by hvoss-techfak

Thanks for creating such a great project. 

I'm currently training on a rather large dataset (500+ GB) of audio data and have found a few optimizations that increase the pre-processing speed in the balance sampler from 10+ minutes down to ~15 seconds and changes to the sampling function to remove the for loop and use only torch functions, that made some pretty big changes for me (from 2 iterations/s to 3.5 iterations/s). 

Both changes produce exactly the same results as before.

2024-10-01 08:51 UTC, AlekseySh commented
Hey, @hvoss-techfak 
thank you for the suggested changes and your interest in OML!

First, let's see if CI is green.

2024-10-01 08:53 UTC, hvoss-techfak commented
I forgot to add the imports. One Second.

2024-10-01 08:54 UTC, AlekseySh commented
Unfortunately, CI is not green, so, please, run tests locally (you will find the commands in the Makefile, you can also check the [Contributing guide](https://open-metric-learning.readthedocs.io/en/latest/oml/contributing.html))

2024-10-01 09:17 UTC, AlekseySh commented
@hvoss-techfak double check linters, please

2024-10-01 09:18 UTC, hvoss-techfak commented
The imports are now fixed, but the tests still give me an error with the "labels = torch.IntTensor(labels)", as apparently not all triplet inputs are given as integers? I'll run the tests locally and check if I can fix this

2024-10-01 09:32 UTC, hvoss-techfak commented
I relaxed the IntTensor to a normal tensor and now all the short tests pass.

2024-10-01 09:35 UTC, AlekseySh commented
let's try one more time

2024-10-01 09:37 UTC, AlekseySh commented
double check linters please

2024-10-01 09:48 UTC, AlekseySh commented
by the way, you can run command "make run_precommit", it will help to fix the linters

2024-10-01 09:57 UTC, AlekseySh commented
@hvoss-techfak seems like the tests are fine now, so I will check the code soon 

could you run all_tests locally please? some my fail (because of environment, OS and so on), but it should be easy to understand if the are related to your changes or not

2024-10-01 10:48 UTC, hvoss-techfak commented
All tests are now done. I had a few that failed because of my ddp setup and some import errors, but apart from that all other tests passed.

2024-10-02 16:10 UTC, DaloroAT requested changes
Hey, @hvoss-techfak

Thank you for your contribution!

I left a couple of comments removing redundant code.

2024-10-02 16:10 UTC, DaloroAT commented on oml/miners/inbatch_hard_tri.py
> +        ids_anchor = torch.arange(batch_size, device=distmat.device)
```
ids_anchor = torch.arange(batch_size, device=distmat.device)
...
return ids_anchor.cpu().tolist(), ...
```
Might be replaced to `ids_anchor = list(range(batch_size))`

2024-10-02 16:10 UTC, DaloroAT commented on oml/miners/inbatch_hard_tri.py
> +        dist_pos[~label_equal] = -float("inf")  # Set non-positives to -inf
`dist_pos[~label_equal]` -> `dist_pos[label_not_equal]`

2024-10-02 16:10 UTC, DaloroAT commented on oml/miners/inbatch_hard_tri.py
> +        dist_neg[~label_not_equal] = float("inf")  # Set non-negatives to +inf
`dist_neg[~label_not_equal]` -> `dist_neg[label_equal]`

2024-10-02 16:16 UTC, DaloroAT commented on oml/miners/inbatch_hard_tri.py
> +        dist_neg[~label_not_equal] = float("inf")  # Set non-negatives to +inf
For this refactoring, this line `label_equal.fill_diagonal_(False)` should be removed 🤔

2024-10-02 16:17 UTC, AlekseySh commented
@hvoss-techfak check out the comments please

2024-10-06 13:13 UTC, hvoss-techfak commented
all changes are done

2024-10-08 16:59 UTC, DaloroAT approved these changes

2024-10-08 20:20 UTC, merged

2024-10-08 20:20 UTC, AlekseySh commented
@DaloroAT thank you for review it!

2024-10-08 20:20 UTC, AlekseySh commented
@hvoss-techfak welcome to the contributors, feel free to work on any issue you like :)